apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-pytorch-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-pytorch-app
  template:
    metadata:
      labels:
        app: ai-pytorch-app
    spec:
      containers:
      - name: ai-pytorch-app
        image: treadlight/ai-pytorch-app:latest
        ports:
        - containerPort: 5000
