name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Check Python version
      run: python --version
    
    - name: Login to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
   
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: app/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ai-pytorch-app:${{ github.sha }}
      

  
  push-image:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ai-pytorch-app:${{ github.sha }}
      
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
